### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by jbgi** [input-output-hk/cardano-byron-proxy#93]
Observed on byron proxy 1.0.3 (`p-{a,b,c}-1`) while cardano-node (`e-a-1`) is running in fixed memory (since https://github.com/input-output-hk/cardano-node/commit/fd62485975f4bfbc1c7ab22cf278ede04962e405):

![byron-proxy-memory-leak](https://user-images.githubusercontent.com/221929/73344598-eb5ace80-4282-11ea-8e8d-d4723d480591.png)

related issue on cardano-node: https://github.com/input-output-hk/cardano-node/issues/460

**Comment by jbgi** [comment]
this is probably fixed in 1.0.4 given first feed-backs of the deployment of 1.0.4 on staging-shelley. waiting a few days to confirm.

**Comment by disassembler** [comment]
new release is confirmed to be handling memory much better. 
![proxy-screenshot](https://user-images.githubusercontent.com/651205/74165397-0b7b7d80-4bf3-11ea-8f75-8b6e885d091d.png)

**Comment by dcoutts** [comment]
That's pretty conclusive. Thanks.
